INSERT INTO [IEB].[dbo].[Mem_Member]
           ([MemberShipNo]
           ,[MemberShipNoDigit]
           ,[Mem_MemberTypeID]
           ,[Name]
           ,[DateOfBirth]
           ,[Age]
           ,[Comn_NationalityID]
           ,[PlaceOfBrith]
           ,[MailingAddress1]
           ,[MailingAddress2]
           ,[MailingAddress3]
           ,[MailingAddress]
           ,[PermanentAddress]
           ,[PermanentAddress1]
           ,[PermanentAddress2]
           ,[PermanentAddress3]
           ,[PhoneOffice]
           ,[PhoneResidence]
           ,[Mobile]
           ,[Email]
           ,[Fax]
           ,[OtherContactInfo]
           ,[Comn_GenderID]
           ,[PresentIEBMembershipNo]
           ,[Mem_SubDivisionID]
           ,[DeclarationDate]
           ,[Mem_ApprovedCouncilMeetingID]
           ,[ScrollNo]
           ,[ReceiptDate]
           ,[CopiesOfCertificates]
           ,[CopiesOfCertificatesComment]
           ,[CopiesOfTranscripts]
           ,[CopiesOfTranscriptsComment]
           ,[PhotoEnclosed]
           ,[ProfessionalRecordEnclosed]
           ,[ProfessionalRecordEnclosedComment]
           ,[RecomendationOffice]
           ,[RecomenDationCommentOffice]
           ,[AgeMembershipSection]
           ,[Education]
           ,[Exprerience]
           ,[RecomendationMembershipSec]
           ,[RecomenDationCommentMembershipSec]
           ,[MembershipSectionEmployeeID]
           ,[Comn_StatusID]
           ,[MembershipCommiteeMemebershipNo]
           ,[MembershipCommiteeMemebershipTypeID]
           ,[PictureURL]
           ,[SignatureURL]
           ,[Comn_UniversityID]
           ,[Comn_DepartmentID]
           ,[PassingYear]
           ,[Comn_OfficeID]
           ,[Comn_BloodGroup]
           ,[PassportNo]
           ,[NationalIDNo]
           ,[BirthRegistrationID]
           ,[ExtraField1]
           ,[ExtraField2]
           ,[ExtraField3]
           ,[ExtraField4]
           ,[ExtraField5]
           ,[ExtraField6]
           ,[ExtraField7]
           ,[ExtraField8]
           ,[ExtraField9]
           ,[ExtraField10]
           ,[ExtraField11]
           ,[ExtraField12]
           ,[ExtraField13]
           ,[ExtraField14]
           ,[ExtraField15]
           ,[ExtraField16]
           ,[ExtraField17]
           ,[ExtraField18]
           ,[ExtraField19]
           ,[ExtraField20]
           ,[AddedBy]
           ,[AddedDate]
           ,[ModifiedBy]
           ,[ModifiedDate]
           ,[Comn_RowStatusID])

Select MembershipNo
           ,MembershipDigit
           ,0
           ,MemName
           ,cast(MemDOB as Date)
           ,0
           ,1
           ,''
           ,''
           ,''
           ,''
           ,MemMailingAddress
           ,MemPerAddress
           ,''
           ,''
           ,''
           ,''
           ,''
           ,MemMobileNo
           ,Email
           ,''
           ,''
           ,MemGender
           ,MemPIEBManuNo
           ,EngFieldCode
           ,EntryDate
           ,1
           ,MemRegNo
           ,GETDATE()
           ,0
           ,''
           ,0
           ,''
           ,0
           ,0
           ,''
           ,0
           ,''
           ,''
           ,''
           ,''
           ,0
           ,''
           ,0
           ,1
           ,0
           ,0
           ,''
           ,''
           ,0
           ,0
           ,0
           ,SubCenterCode+16
           ,0
           ,''
           ,''
           ,''
           ,''
           ,''
           ,''
           ,''
           ,''
           ,''
           ,''
           ,''
           ,''
           ,''
           ,''
           ,''
           ,''
           ,''
           ,''
           ,''
           ,''
           ,''
           ,''
           ,''
           ,1
           ,GETDATE()
           ,1
           ,GETDATE()
           ,1
           FROM [IEBDB].[dbo].[MembershipRegistrationInfo]


