INSERT INTO [All]([No],[GroupName]) select No,'aftermember' from aftermember
INSERT INTO [All]([No],[GroupName]) select No,'agrildhaka' from agrildhaka
INSERT INTO [All]([No],[GroupName]) select No,'bbandhu' from bbandhu
INSERT INTO [All]([No],[GroupName]) select No,'benevolent' from benevolent
INSERT INTO [All]([No],[GroupName]) select No,'ccm' from ccm
INSERT INTO [All]([No],[GroupName]) select No,'ccm2014' from ccm2014
INSERT INTO [All]([No],[GroupName]) select No,'centralcouncil1' from centralcouncil1
INSERT INTO [All]([No],[GroupName]) select No,'children' from children
INSERT INTO [All]([No],[GroupName]) select No,'civilfull' from civilfull
INSERT INTO [All]([No],[GroupName]) select No,'dhakacentre' from dhakacentre
INSERT INTO [All]([No],[GroupName]) select No,'digital' from digital
INSERT INTO [All]([No],[GroupName]) select No,'electrical' from electrical
INSERT INTO [All]([No],[GroupName]) select No,'enggdivision' from enggdivision
INSERT INTO [All]([No],[GroupName]) select No,'epsswfull' from epsswfull
INSERT INTO [All]([No],[GroupName]) select No,'esw2013' from esw2013
INSERT INTO [All]([No],[GroupName]) select No,'executivecom' from executivecom
INSERT INTO [All]([No],[GroupName]) select No,'exeepsswc' from exeepsswc
INSERT INTO [All]([No],[GroupName]) select No,'extraccouncil' from extraccouncil
INSERT INTO [All]([No],[GroupName]) select No,'fellowmobile' from fellowmobile
INSERT INTO [All]([No],[GroupName]) select No,'fullvotersms' from fullvotersms
INSERT INTO [All]([No],[GroupName]) select No,'iebhalf' from iebhalf
INSERT INTO [All]([No],[GroupName]) select No,'jamil' from jamil
INSERT INTO [All]([No],[GroupName]) select No,'kashem' from kashem
INSERT INTO [All]([No],[GroupName]) select No,'latest' from latest
INSERT INTO [All]([No],[GroupName]) select No,'localcouncilda' from localcouncilda
INSERT INTO [All]([No],[GroupName]) select No,'mechmisc' from mechmisc
INSERT INTO [All]([No],[GroupName]) select No,'mechtel' from mechtel
INSERT INTO [All]([No],[GroupName]) select No,'memberelect' from memberelect
INSERT INTO [All]([No],[GroupName]) select No,'membermobile' from membermobile
INSERT INTO [All]([No],[GroupName]) select No,'miscellionous' from miscellionous
INSERT INTO [All]([No],[GroupName]) select No,'misclist' from misclist
INSERT INTO [All]([No],[GroupName]) select No,'miscsw' from miscsw
INSERT INTO [All]([No],[GroupName]) select No,'mmq1' from mmq1
INSERT INTO [All]([No],[GroupName]) select No,'mmq2' from mmq2
INSERT INTO [All]([No],[GroupName]) select No,'mmquayyum' from mmquayyum
INSERT INTO [All]([No],[GroupName]) select No,'mohilacommittee' from mohilacommittee
INSERT INTO [All]([No],[GroupName]) select No,'newfm2013' from newfm2013
INSERT INTO [All]([No],[GroupName]) select No,'nseminarc' from nseminarc
INSERT INTO [All]([No],[GroupName]) select No,'textile' from textile
INSERT INTO [All]([No],[GroupName]) select No,'various' from various
INSERT INTO [All]([No],[GroupName]) select No,'votefm' from votefm
INSERT INTO [All]([No],[GroupName]) select No,'voter' from voter

